load("@rules_shell//shell:sh_binary.bzl", "sh_binary")
load("//tools:deps.bzl", "cdeps", "python_ide_backport")
load("@pypi//:requirements.bzl", "requirement")
load("@aspect_rules_py//py:defs.bzl", "py_binary", "py_library")

py_library(
    name = "he6_cres_spec_sims",
    srcs = glob(["**/*.py"]),
    visibility = ["//visibility:public"],
    deps = cdeps([
        requirement("argparse"),
        requirement("awkward-pandas"),
        requirement("pandas"),
        requirement("psycopg2-binary"),
        requirement("pytz"),
        requirement("pyyaml"),
        requirement("scikit-learn"),
        requirement("uproot"),
    ]),
)

python_ide_backport()
